Issue #215 Fix: report correct job status in _list_job_results when p…
Open-EO/openeo-python-driver pull request #224
Opened 2023-09-08 09:01 UTC by JohanKJSchreurs

## Issue #215 Fix: report correct job status in _list_job_results when partial=true

This PR corrects the reported job status for some cases in the context of https://github.com/Open-EO/openeo-geopyspark-driver/issues/489, as noted by  @bossie, here: https://github.com/Open-EO/openeo-python-driver/issues/215#issuecomment-1682261335 .

- if partial and job error/canceled -> openeo:status running (expected: error/canceled)
- if partial and job finished -> no openeo:status (expected: finished)
- if not partial and job error/canceled -> JobNotFinishedException; after some contemplating I believe this is still OK as the back-end is not required to return intermediate results.

### Solution in brief:

Basically we should report the actual job status when partial is true, and also include openeo:status when the job is finished. 
- When partial is false and the jobs is not finished, do the same as before: raise JobNotFinishedException.

2023-09-26 13:14 UTC, bossie requested changes
Added remarks inline.

2023-09-26 13:14 UTC, bossie commented on openeo_driver/views.py
> +                    openeo_status = "created"
According to https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/list-results, the allowed values for "openeo:status" are: "running" "canceled" "finished" "error" so you'll want to map job statuses "queued" and "created" to "openeo:status" "running" instead.

2023-09-26 13:14 UTC, bossie commented on openeo_driver/views.py
> +                    "openeo:status": openeo_status,
I'm getting this warning in Pycharm:

> Local variable 'openeo_status' might be referenced before assignment

so maybe add something like this:
```
else:
    raise AssertionError(f"unexpected job status {job_info.status}")
```

2023-09-27 14:46 UTC, JohanKJSchreurs commented on openeo_driver/views.py
> +                    "openeo:status": openeo_status,
Added the exception, and added a test for it as well.

2023-09-29 09:43 UTC, bossie approved these changes
Looks great.

2023-09-29 09:44 UTC, merged