Apply changes again on new branch. Upload on wheels.
Open-EO/openeo-python-driver pull request #246
Opened 2024-01-16 13:41 UTC by EmileSonneveld

https://github.com/Open-EO/openeo-geopyspark-driver/issues/616

2024-01-16 13:41 UTC, EmileSonneveld commented
For https://github.com/Open-EO/openeo-geopyspark-driver/issues/616

2024-01-17 08:48 UTC, soxofaan requested changes

2024-01-17 08:52 UTC, soxofaan commented on openeo_driver/_version.py
> +__version__ = "0.80.666"
Turns out this build indeed has leaked in production/integration tests

2024-01-17 08:52 UTC, jdries approved these changes

2024-01-17 08:55 UTC, soxofaan requested changes

2024-01-17 08:55 UTC, soxofaan commented on Jenkinsfile
> +  upload_dev_wheels = true
this should be reset before merging in master

2024-01-17 09:02 UTC, merged